module_name="TestFstream"

#input = [ "iosfwd", "fstream", "fstream_def.h" ]
input = [ "fstream_def.h" ]

extra_headers = [ "streambuf" ]
		  
#include_dirs = [ ".", "/usr/lib/llvm-11/include/c++/v1"  ]
include_dirs = [ "." ]

cxx-std = "c++17"

auto_veto = false

#clang_opts = [ "-stdlib=libc++" ]

#macro_definitions = [ "CXXWRAPGEN" ]



# all generated code in a single file:
n_classes_per_file = 0
