module_name         = "TestStringView"

include_dirs        = [ "." ]

input               = [ "A.h" ]

#extra_headers       = [  ]

cxx-std             = "c++17"

export  = "all"

auto_veto = false

# all generated code in a single file:
n_classes_per_file = 0

