module_name="TestPropagation2"

propagation_mode = "types"

input = [ "B2.h" ]

include_dirs = [ "." ]

extra_headers = [  ]

cxx-std = "c++17"

export = "all"

# all generated code in a single file:
n_classes_per_file = 0
