module_name="TestPropagation2"
uuid                = "9d9b0f37-9d0a-4dc4-a44d-0b7f029205ea"

propagation_mode = "types"

input = [ "B2.h" ]

include_dirs = [ "." ]

extra_headers = [  ]

cxx-std = "c++17"

export = "all"

# all generated code in a single file:
n_classes_per_file = 0
