module_name="TestPropagation1"
uuid                = "dcafd7d8-bc61-4afa-8d46-2a065f56244d"

propagation_mode = "types"

input = [ "B1.h" ]

include_dirs = [ "." ]

extra_headers = [ "A.h" ]

cxx-std = "c++17"

export = "all"

# all generated code in a single file:
n_classes_per_file = 0
