module_name = "TestTemplate2"
uuid                = "f6352dd4-e1f8-479c-b32e-3de4d6ebae5d"

input = [ "A.h" ]
		  
include_dirs = [ "." ]

auto_veto = true

cxx-std = "c++17"

export = "all"

# all generated code in a single file:
n_classes_per_file = 0
