module_name         = "TestPointers"
uuid                = "349e78bd-0c7e-4b4e-b557-74e6dbc0705f"

include_dirs        = [ "." ]

input               = [ "A.h" ]

cxx-std             = "c++17"

export  = "all"

# all generated code in a single file:
n_classes_per_file = 0
