module_name         = "TestCtorDefVal"
uuid                = "6adbae56-dcac-43a4-a141-f1a93695edd0"

include_dirs        = [ "." ]

input               = [ "A.h" ] 

cxx-std             = "c++17"

# all generated code in a single file:
n_classes_per_file = 0
