module_name         = "TestStdVector"
uuid                = "e3f6a139-b70f-4986-83d9-6831a1366ac5"

include_dirs        = [ "."  ]

input               = [ "A.h" ]

cxx-std             = "c++17"

export = "all"

fields_and_variables = false

# all generated code in a single file:
#n_classes_per_file = 0

# not working with CxxWrap 0.16 on MacOS and with 0.15 on both Linux and MacOS
# forcing version to 0.14
cxxwrap_version = "0.14"

