module_name         = "TestVarFieldOff"
uuid                = "d452198e-6ce7-4520-8180-a0cb7a6fd7a6"

input               = [ "A.h" ] 

include_dirs        = [ "." ]

cxx-std             = "c++17"

# all generated code in a single file:
n_classes_per_file = 0

fields_and_variables = false
