module_name         = "TestVarFieldOn"

input               = [ "A.h" ] 

include_dirs        = [ "." ]

cxx-std             = "c++17"

export = "all"

# all generated code in a single file:
n_classes_per_file  = 0

fields_and_variables = true

auto_veto            = false