module_name         = "TestVarFieldOn"
uuid                = "dd714936-ccd5-4eb9-b517-eb27dc33182c"

input               = [ "A.h" ] 

include_dirs        = [ "." ]

cxx-std             = "c++17"

export = "all"

# all generated code in a single file:
n_classes_per_file  = 0

fields_and_variables = true

auto_veto            = false
