module_name="TestTemplate1"
uuid                = "75b462a2-300d-4e17-8fef-26b5867f20b8"

input = [ "A.h" ]
		  
include_dirs = [ "." ]

cxx-std = "c++17"

auto_veto = false

export = "all"

# all generated code in a single file:
n_classes_per_file = 0
