module_name         = "TestNoFinalizer"
uuid                = "9b3b33f9-5f5a-4340-99f2-99014b361dcb"

include_dirs        = [ "." ]

input               = [ "A.h" ]

vetoed_finalizer_classes = [ "B", "X" ]

cxx-std             = "c++17"
# all generated code in a single file:
n_classes_per_file = 0
