module_name         = "TestSizet"
uuid                = "2c12789d-13f2-429a-adac-3a38cadcc931"

include_dirs        = [ "." ]

input               = [ "A.h" ]

#extra_input         = [ "cstdef" ]

cxx-std             = "c++17"

export  = "all"

auto_veto = true

# all generated code in a single file:
n_classes_per_file = 0

