module_name         = "TestAccessAndDelete"
uuid                = "b84a21c7-7db1-4fd8-bb99-b65182dd0d09"

include_dirs        = [ "." ]

input               = [ "TestAccessAndDelete.h" ] 

cxx-std             = "c++17"

export = "all"

# all generated code in a single file:
n_classes_per_file = 0
