module_name="TestNamespace"
uuid                = "9105eb7d-8b5e-4e93-a689-47fa8b474c60"

input = [ "A.h" ]
		  
include_dirs = [ "." ]

cxx-std = "c++17"

auto_veto = false

export = "all"

# all generated code in a single file:
n_classes_per_file = 0
