module_name         = "ROOT"
uuid                = "b0506e13-49c2-4ce6-b48c-bb2bc691fb3e"
version             = "0.0.1"

export_jl_fname     = "ROOT-export.jl"
module_jl_fname     = "ROOT-generated.jl"
lib_basename        = "$(@__DIR__)/../deps/libjlROOT"

include_dirs        = [ "%ROOT_INC_DIR%", "." ]

input               = [ "TTree.h", "TBranchPtr.h", "TSystem.h", "TCanvas.h", "TROOT.h", "TAttLine.h", "TAttFill.h", "TH1.h", "TRandom.h", "TAxis.h", "TApplication.h",  "TDirectoryFile.h", "TFile.h", "TNamed.h", "TObject.h", "TGraph.h", "TF1.h", "TTreeReader.h", "TTreeReaderValue.h", "TTreeReaderArray.h", "Templates.h", "TEntryList.h",  "TVectorT.h", "TVectorDfwd.h", "TVectorFfwd.h"  ]
#input               = [  "TTreeReader.h", "TTreeReaderValue.h", "TTreeReaderArray.h" ]
extra_headers       = [ "TVectorT.h" ]

veto_list           = "jlROOT-veto.h"

class_order_constraints = [ "TTreeReader < TTreeReaderValue" ]

fields_and_variables = false

# Not working with CxxWrap 0.15.0, use 0.17.x
cxxwrap_version = "0.17"

#auto_veto           = false

vetoed_copy_ctor_classes = [ "TTreeReader", "RDataFrame" ]

cxx-std             = "c++17"

inheritances        = [ "TROOT:" ]

export_blacklist    = [ "Integer", "Set", "Timer", "cd", "mkdir", "pwd", "begin", "end" ]

n_classes_per_file  = 10

vetoed_finalizer_classes = [ "TTree" ]
