#CXXFLAGS += -DVERBOSE_IMPORT #To enable the verbose mode of the libray loading
#CXXFLAGS += -Wall -O0 -g     #To compile with debugger infomation

MODULE_NAME=TestOrder
EXTRA_OBJS=A.o

-include ../make.rules

WRAPIT_VERBOSITY=1
