module_name         = "TestIncompleteArray"
uuid                = "ccef8bff-c5fb-42fc-a1e7-2ad4b6b12870"

include_dirs        = [ "." ]

input               = [ "A.h" ]

cxx-std             = "c++17"

export = "all"

# all generated code in a single file:
n_classes_per_file = 0
