module_name         = "TestUsingType"
uuid                = "0ba2e2b8-09e1-4537-a510-6ba872e04e29"

include_dirs        = [ "." ]

input               = [ "A.h" ]

#extra_input         = [ "cstdef" ]

cxx-std             = "c++17"

export  = "all"

auto_veto = true

# all generated code in a single file:
n_classes_per_file = 0

# not working with CxxWrap 0.16 on MacOS
# forcing version to 0.14
cxxwrap_version = "0.14"
