module_name         = "TestAutoAdd"
uuid                = "21166305-f8c1-4e69-baf1-f0db5e7eeaa1"

include_dirs        = [ "." ]

input               = [ "A.h" ]

#extra_input         = [ "cstdef" ]

cxx-std             = "c++17"

export  = "all"

auto_veto = true

# all generated code in a single file:
n_classes_per_file = 0

