module_name         = "TestInheritance"
uuid                = "e64be293-bed8-4ae4-84f8-1bc3a2c4f291"

include_dirs        = [ "." ]

input               = [ "A.h", "D.h", "MyString.h" ]

cxx-std             = "c++17"

# all generated code in a single file:
n_classes_per_file = 0

# test inheritance map
inheritances = [ "B2:A2", "F:" ]